config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#index"
  resources :jobs, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.includes(:tag).all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
    @tags = Tag.order(:name)
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to job_path(@job)
    else
      render 'new'
    end
  end

  private
  def job_params
    params.require(:job).permit(:name, :status, :tag_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/dashboard/index.html.erb
<h1 class="text-6xl font-bold">Hotwire demo</h1>
<%= link_to 'List of jobs', jobs_path, class: "underline mt-5 block" %>

app/views/jobs/index.html.erb
<section class="bg-white p-20 rounded-lg shadow-2xl w-full">
  <h1 class="text-3xl font-bold">List of jobs</h1>
  <%= link_to 'Create new job', new_job_path, class: "block py-6 underline" %>
  <table class="border border-collapse border-slate-400 w-96">
    <thead>
    <tr>
      <th class="border border-slate-400 text-left px-2 py-3">Name</th>
      <th class="border border-slate-400 text-left px-2 py-3">Status</th>
      <th class="border border-slate-400 text-left px-2 py-3">Tag</th>
    </tr>
    </thead>
    <tbody>
    <% @jobs.each do |j| %>
      <tr>
        <td class="border border-slate-400 text-left px-2 py-3"><%= j.name %></td>
        <td class="border border-slate-400 text-left px-2 py-3"><%= j.status %></td>
        <td class="border border-slate-400 text-left px-2 py-3"><%= j.tag.name %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/jobs/new.html.erb
<section class="bg-white p-20 rounded-lg shadow-2xl w-96">
  <h1 class="text-3xl font-bold mb-6">New job</h1>
  <%= form_with model: @job do |form| %>
    <div class="mb-2">
      <%= form.label :name, "Role", class: "block font-semibold" %>
      <%= form.text_field :name, class: "w-full rounded" %>
    </div>
    <div class="mb-2">
      <%= form.label :status, class: "block font-semibold" %>
      <%= form.text_field :status, class: "w-full rounded" %>
    </div>
    <div class="mb-2">
      <%= form.label :tag, class: "block font-semibold" %>
      <%= form.collection_select :tag_id, @tags, :id, :name, {}, { class: "w-full rounded" } %>
    </div>
    <%= form.submit "Save job", class: "mt-7 bg-black text-white rounded w-full py-3 font-semibold" %>
  <% end %>
</section>

app/views/jobs/show.html.erb
<h1><%= @job.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hotwire Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100 flex h-screen justify-center items-center">
    <main>
      <%= yield %>
    </main>
  </body>
</html>